<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{183ba2ae-5ddc-4dea-9599-53c21335e6f8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nCounter 	: INT;
	fbTest		: FB_Test;
	fbTest2		: FB_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nCounter := nCounter + 1;
fbTest();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>